#!/bin/bash

#Test String
#str="THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"
# str="abcdefghijklmnopqrstuvwxyz"

read str;

pattern=$(./create_pattern $@) #Get the pattern
if (( $# > 2 )) #Check if uppercase needed
then
    echo $str | tr '[A-Z]' $pattern
else
    echo $str | tr '[a-z]' $pattern
fi