#!/bin/bash

#Test String
#str="THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"
# str="abcdefghijklmnopqrstuvwxyz"
pattern=$(./create_pattern $@) #Get the pattern
done=false
until $done ;do #Get input until EOF
read str || done=true
    if (( $# > 2 )) #Check if uppercase needed
    then
        echo $str | tr '[A-Z]' $pattern
    else
        echo $str | tr '[a-z]' $pattern
    fi
done