#!/bin/bash
count=0
upper=0

if (($# > 2))
then
    let upper=1 #Check if change uppercase
fi

while (($#))
do
    if (($1 > 0)) #Get number of shifting
    then
        let count=$1;
    fi
    shift
done

if (($count == 0 || $count == 26)) #Edge case
then
    if (($upper == 1))
    then
        printf "[A-Z]"
    else
        printf "[a-z]"
    fi
elif (($upper == 1))
then
    start=`printf "%d" "'A"`; #Get character as number
    let start=$start+$count;
    if (($start > 90))
    then
        let start=$((start-26));
    fi
    let end=$start-1;
    printf "[\x$(printf %x $start)" #Print in special format
    printf "%cZA%c" '-' '-'
    printf "\x$(printf %x $end)]"
else
    start=`printf "%d" "'a"`;
    let start=$start+$count;
    if (($start > 122))
    then
        let start=$((start-26));
    fi
    let end=$start-1;
    printf "[\x$(printf %x $start)"
    printf "%cza%c" '-' '-'
    printf "\x$(printf %x $end)]"
fi