#!/bin/bash

#str="THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"
# str="abcdefghijklmnopqrstuvwxyz"
read str
count=0
num=0
upper=0

for i in $@
do
    if [ $i = "-u" ]
    then
        let upper=1;
    fi

    if (($i <= 26 && $i >= 0))
    then
        let count=$i;
    fi
done

for ((i = 0; i < ${#str}; i++))
do
    v=`printf "%d" "'${str:$i:1}"`;
    if (( ($v >= 65 && $v <= 90) || ($v >= 97 && $v <= 122) ))
    then
        if (($upper == 1))
        then
            if (($v+$count <= 90))
            then
                let v=$v+$count;
            else
                let v=$v+$count-90+65-1;
            fi
        else
            if (($v+$count <= 122))
            then
                let v=$v+$count;
            else
                let v=$v+$count-122+97-1;
            fi
        fi
    fi
    printf "\x$(printf %x $v)"
done
echo