#!/bin/bash
upper=0
for i in $@
do
    if (($i == "n"))
    then
        continue
    fi

    if (($i == "u"))
    then
        echo "TEST"
        let upper=1; #Check if we need to change upper case
    fi

    if (($i <= 26 && $i >= 0))
    then
        let count=$i; #Get the shifting position
    fi
done

if (($upper == 1))
then
    start=`printf "%d" "'A"`; #Get character as number
    let start=$start+$count;
    if (($start > 90))
    then
        let start=$((start-26));
    fi
    let end=$start-1;
    printf "[\x$(printf %x $start)"
    printf "%cZA%c" '-' '-'
    printf "\x$(printf %x $end)]"
else
    start=`printf "%d" "'a"`;
    let start=$start+$count;
    if (($start > 122))
    then
        let start=$((start-26));
    fi
    let end=$start-1;
    printf "[\x$(printf %x $start)"
    printf "%cza%c" '-' '-'
    printf "\x$(printf %x $end)]"
fi
echo