#!/bin/bash

#Test String
#str="THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"
# str="abcdefghijklmnopqrstuvwxyz"

for ((i=1; i < 26; i++))
do
    echo "Shift $i"
    echo $( ./caesar -u -n $i < $1 ) #Pass the file to caesar
done